name: Lint and Auto-Fix Code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Python Auto-fix and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install autopep8 and flake8
        run: |
          pip install autopep8 flake8

      - name: Auto-fix with autopep8
        run: |
          autopep8 . --in-place --recursive --aggressive --aggressive

      - name: Run Flake8 Linter
        run: |
          echo "Running Flake8 on all Python files..."
          flake8
          echo "✅ Linted all Python files successfully"

  lint_js:
    name: JavaScript Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run JSHint Linter
        run: |
          echo "Running JSHint on all JavaScript files..."
          find . -name "*.js" -exec jshint {} +
          echo "✅ Linted all JavaScript files successfully"
